name: Alliser

on: [pull_request]

jobs:
  alliser:
    runs-on: ubuntu-latest
    name: Check file types
    steps:
    - uses: actions/checkout@v2
    - uses: stscoundrel/alliser-action@v0.7.0
      name: Alliser action step
      with:
        extensions: .ts,.tsx,.scss,.snap
        folders: src,tests/unit
